name: Cryptol Nightly Builds
on:
  push:
    branches:
      - "actions/*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  outputs:
    runs-on: ubuntu-latest
    outputs:
      cryptol-version: ${{ steps.cryptol.outputs.cryptol-version }}
      cryptol-name: ${{ steps.cryptol.outputs.cryptol-name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: cryptol
        run: |
          ver="$(grep Version cryptol.cabal | awk '{print $2}')"
          echo "::set-output name=cryptol-version::$ver"
          d="$(date -I)"
          echo "::set-output name=cryptol-name::cryptol-$ver-$d"

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:latest
        with:
          args: >-
            sh -c
            "
            apk add make &&
            tlmgr install subfigure lastpage preprint adjustbox nag collectbox sectsty todonotes palatino mathpazo &&
            cd docs &&
            make
            "
      - uses: actions/upload-artifact@v2
        with:
          path: docs
          name: docs

  build:
    needs: [outputs, docs]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "8.8"

      - uses: actions/download-artifact@v2
        with:
          path: docs
          name: docs

      - shell: bash
        # path stuff is a temporary workaround until setup-haskell is fixed.
        run: |
          export PATH=~/.ghcup/ghc/8.8.3/bin:$PATH
          echo "::set-env name=PATH::$PATH"
          .github/ci.sh build

      - shell: bash
        run: .github/ci.sh setup_dist_bins

      - if: runner.os == 'Windows'
        env:
          VERSION: ${{ needs.outputs.outputs.cryptol-version }}
        run: .github/wix.ps1

      - uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ needs.outputs.outputs.cryptol-name }}-${{ runner.os }}

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
          path: cryptol.msi
          name: cryptol.msi
